/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/fe619885-ba9d-41d5-b4b2-c527b9ca6fb9 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool machineAInUse;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

const long updateInterval = 10000;
unsigned long lastUpdateTime = 0;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  if (millis() - lastUpdateTime > updateInterval) {
    machineAInUse = (random(2) == 1) ? true : false;
    Serial.print("machineAInUse updated to: ");
    Serial.println(machineAInUse);
    lastUpdateTime = millis();
  }
}

/*
  Since MachineAInUse is READ_WRITE variable, onMachineAInUseChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMachineAInUseChange()  {
  // Add your code here to act upon MachineAInUse change
}